default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: myapp_development
  username: myuser
  password: mypassword
  host: db
  port: 3306

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "myapp_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD", "myapp_production") %>
